# Generated by Django 3.2.25 on 2024-10-21 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ESP32Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=50)),
                ('log_message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='soildata',
            name='sender1_ph',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='soildata',
            name='sender2_ph',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
