# Generated by Django 3.2.25 on 2024-10-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soil', '0002_auto_20241021_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soildata',
            name='sender1_ph',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='soildata',
            name='sender2_ph',
            field=models.FloatField(null=True),
        ),
    ]
